version: "3.5"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
  app:
    container_name: fastapi-pg
    restart: always
    build: ./
    command: bash -c "alembic upgrade head && uvicorn app.main.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - ../:/app
      - /etc/localtime:/etc/localtime
    # networks:
    #   - app_network
    depends_on:
      - db  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db  
# networks:
#   app_network:
#     driver: bridge