version: "3.5"
services:
  app:
    container_name: fastapi-intro
    build: ./
    ports:
      - 80:80
    volumes:
      - ../:/home/app
      - /etc/localtime:/etc/localtime
    networks:
      - app_network
networks:
  app_network:
    driver: bridge